### ISSUE TITLE
Poor contrast for selecting text in terminal with current background color for dark schemes

### ISSUE THREAD

**Issue by arrrgi** [anihm136/zellij#1]
### Expected result

Selecting text in a Zellij pane should provide feedback to the user by having enough contrast between the background/black and foreground colors

**Screenshot**

![CleanShot 2024-01-11 at 11 46 59](https://github.com/rose-pine/zellij/assets/18177842/698dbe7a-e6da-4408-a754-c1281ce776af)

### Current behaviour

It isn't currently possible to distinguish whether text has been highlighted for selection in a Zellij pane

**Screenshot**

![CleanShot 2024-01-11 at 11 51 22](https://github.com/rose-pine/zellij/assets/18177842/c96c90f7-ee43-44bd-b266-0caa8b66881f)

### Proposed fix

_Discussion:_ I think choosing to swap the current background color from the palette (currently using `Base #191724`) with `Highlight Med #403d52` will provide a muted but sufficient contrast that the user can see what text has been selected.

### Environment

**Operating System:** MacOS 14.2.1
**Zellij version:** zellij 0.39.2
**Terminal emulator:** WezTerm 20230712-072601-f4abf8fd

### Config output
```console
$cat .config/zellij/config.kdl

// Define color themes for Zellij
// For more examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
// Once these themes are defined, one of them should to be selected in the "theme" section of this file
//
//themes {
//    dracula {
//        fg 248 248 242
//        bg 40 42 54
//        red 255 85 85
//        green 80 250 123
//        yellow 241 250 140
//        blue 98 114 164
//        magenta 255 121 198
//        orange 255 184 108
//        cyan 139 233 253
//        black 0 0 0
//        white 255 255 255
//    }
//}

// Choose the theme that is specified in the themes section.
// Default: default
//
theme "rose-pine"

ui {
    pane_frames {
        rounded_corners true
    }
}
```

```console
$cat .config/zellij/themes/rose-pine.kdl
themes {
        rose-pine {
                bg "#191724"
                fg "#e0def4"
                red "#eb6f92"
                green "#31748f"
                blue "#9ccfd8"
                yellow "#f6c177"
                magenta "#c4a7e7"
                orange "#fe640b"
                cyan "#ebbcba"
                black "#26233a"
                white "#e0def4"
        }
}
```

**Comment by anihm136** [comment]
Thanks for catching this!

**Comment by arrrgi** [comment]
You're welcome. I haven't checked whether the Dawn theme has the same challenge, if I do decide to switch I'll make a new PR if I find the same problem.
